const alphabet = [
  { letter: 'ا', sound: 'Alif', example: 'as in "arm"' },
  { letter: 'ب', sound: 'Be', example: 'as in "ball"' },
  { letter: 'پ', sound: 'Pe', example: 'as in "pen"' },
  { letter: 'ت', sound: 'Te', example: 'as in "top"' },
  { letter: 'ٹ', sound: 'Ṭe', example: 'retroflex T' },
  { letter: 'ث', sound: 'Se', example: 'as in "sun"' },
  { letter: 'ج', sound: 'Jeem', example: 'as in "jam"' },
  { letter: 'چ', sound: 'Che', example: 'as in "chin"' },
  { letter: 'ح', sound: 'Baṛī He', example: 'breathy H' },
  { letter: 'خ', sound: 'Khe', example: 'as in "loch"' },
  { letter: 'د', sound: 'Daal', example: 'as in "dog"' },
  { letter: 'ڈ', sound: 'Ḍaal', example: 'retroflex D' },
  { letter: 'ذ', sound: 'Zaal', example: 'as in "zoo"' },
  { letter: 'ر', sound: 'Re', example: 'as in "run"' },
  { letter: 'ڑ', sound: 'Ṛe', example: 'retroflex R' },
  { letter: 'ز', sound: 'Ze', example: 'as in "zebra"' },
  { letter: 'ژ', sound: 'Zhe', example: 'as in "measure"' },
  { letter: 'س', sound: 'Seen', example: 'as in "sun"' },
  { letter: 'ش', sound: 'Sheen', example: 'as in "shoe"' },
  { letter: 'ص', sound: 'Suaad', example: 'emphatic S' },
  { letter: 'ض', sound: 'Zuaad', example: 'emphatic Z' },
  { letter: 'ط', sound: 'Toe', example: 'emphatic T' },
  { letter: 'ظ', sound: 'Zoe', example: 'emphatic Z' },
  { letter: 'ع', sound: 'Ain', example: 'guttural stop' },
  { letter: 'غ', sound: 'Ghain', example: 'as in French "r"' },
  { letter: 'ف', sound: 'Fe', example: 'as in "fan"' },
  { letter: 'ق', sound: 'Qaaf', example: 'deep K sound' },
  { letter: 'ک', sound: 'Kaaf', example: 'as in "kite"' },
  { letter: 'گ', sound: 'Gaaf', example: 'as in "go"' },
  { letter: 'ل', sound: 'Laam', example: 'as in "lamp"' },
  { letter: 'م', sound: 'Meem', example: 'as in "moon"' },
  { letter: 'ن', sound: 'Noon', example: 'as in "night"' },
  { letter: 'ں', sound: 'Noon Ghunna', example: 'nasal N' },
  { letter: 'و', sound: 'Wao', example: 'as in "wave"' },
  { letter: 'ہ', sound: 'Choṭī He', example: 'as in "hat"' },
  { letter: 'ھ', sound: 'Do Chashmi He', example: 'aspirating H' },
  { letter: 'ء', sound: 'Hamza', example: 'glottal stop' },
  { letter: 'ی', sound: 'Choṭī Ye', example: 'as in "yes"' },
  { letter: 'ے', sound: 'Baṛī Ye', example: 'as in "day"' },
];

export default alphabet;
